
// import "./globals.css";

import Link from "next/link";
import RootNavigation from "./_components/RootNavigation";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RootNavigation />
        {children}
      </body>
    </html>
  );
}
